// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhuzvaoakknmswxcwfwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhodXp2YW9ha2tubXN3eGN3ZndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTk2OTAsImV4cCI6MjA2MTczNTY5MH0.FLUpB9xgeBbesas4wHjpQLn81kiWIuMH-radi6DSO1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);